# Site settings
title: The Next Four Years.
email: jola2372@cs.ubc.ca
description: An overview of my programming portfolio, and research interests.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://wilderlavington.github.io" # the base hostname & protocol for your site
github_username:  wilderlavington
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
